### ISSUE TITLE
[bug]2022-12-12 link rank error

### ISSUE THREAD

**Issue by tower-town** [tower-town/Koala-Hacker-News#8]
> 提要：这是一个隐患问题，链接有无与bilibili的审核、up主有无上传，存在例外的链接位置

**Comment by tower-town** [comment]
这一期是因为bilibili评论区缺失了这一期的一个链接的内容

**Comment by tower-town** [comment]
需要找到一个比较稳妥的处理的办法，而不是获取评论区的一种方式

**Comment by ZutJoe** [comment]
我觉得人工补充会比较好，虽然笨，但是快
因为我们不会知道下一次又是以什么样的方式出现内容无法爬取的情况

**Comment by tower-town** [comment]
> 我觉得人工补充会比较好，虽然笨，但是快 因为我们不会知道下一次又是以什么样的方式出现内容无法爬取的情况

目前有一个草案就是：通过爬取 HackerNews 网站的数据来补充。具体方法是：使用Koala简介的英文关键字在HackerNews网站爬取最新一期的链接，但HackerNews 网站貌似被ban了，debug的时候比较麻烦

**Comment by ZutJoe** [comment]
> HackerNews 网站貌似被ban了，debug的时候比较麻烦

你都能上github了，HackerNews怎么上不去

**Comment by tower-town** [comment]
github我是靠`fastgithub`，不是科学上网

**Comment by tower-town** [comment]
> > HackerNews 网站貌似被ban了，debug的时候比较麻烦
> 
> 你都能上github了，HackerNews怎么上不去

github 我是靠`fastgithub`，不是科学上网

**Comment by ZutJoe** [comment]
> github 我是靠`fastgithub`，不是科学上网

行吧

**Comment by tower-town** [comment]
> > github 我是靠`fastgithub`，不是科学上网
> 
> 行吧

未来我看看有没有办法

**Comment by ZutJoe** [comment]
> > > github 我是靠`fastgithub`，不是科学上网
> > 
> > 
> > 行吧
> 
> 未来我看看有没有办法

嗯嗯
